In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras

In [21]:
 tf.config.experimental.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [22]:
tf.test.is_built_with_cuda()

False

In [23]:
(x_train,y_train),(x_test,y_test)=keras.datasets.cifar10.load_data()

In [24]:
x_train.shape

(50000, 32, 32, 3)

In [25]:
def plot_sample(index):
    plt.figure(figsize=(10,1))
    plt.imshow(x_train[index])
    

In [26]:
classes=["airplane","automobile","bird","cat","bird","cat","deer","frog","horse","ship","tree"]
classes

['airplane',
 'automobile',
 'bird',
 'cat',
 'bird',
 'cat',
 'deer',
 'frog',
 'horse',
 'ship',
 'tree']

In [27]:
x_train_scaled=x_train/255
x_test_scaled=x_test/255

In [28]:
x_test_scaled[0][0]

array([[0.61960784, 0.43921569, 0.19215686],
       [0.62352941, 0.43529412, 0.18431373],
       [0.64705882, 0.45490196, 0.2       ],
       [0.65098039, 0.4627451 , 0.20784314],
       [0.62745098, 0.43921569, 0.18039216],
       [0.61176471, 0.42745098, 0.16078431],
       [0.63529412, 0.45098039, 0.18431373],
       [0.62352941, 0.44313725, 0.17647059],
       [0.61960784, 0.43529412, 0.17254902],
       [0.62352941, 0.44313725, 0.16078431],
       [0.63137255, 0.45490196, 0.16078431],
       [0.62745098, 0.43529412, 0.20392157],
       [0.63137255, 0.43529412, 0.19215686],
       [0.65098039, 0.45882353, 0.16078431],
       [0.6627451 , 0.45882353, 0.17647059],
       [0.66666667, 0.46666667, 0.17254902],
       [0.65490196, 0.45882353, 0.15686275],
       [0.63529412, 0.44313725, 0.14901961],
       [0.62745098, 0.43529412, 0.15294118],
       [0.62745098, 0.43921569, 0.16862745],
       [0.61176471, 0.42745098, 0.17254902],
       [0.58431373, 0.41960784, 0.17647059],
       [0.

In [29]:
y_train_categorical=keras.utils.to_categorical(
    y_train, num_classes=10
)
y_train_categorical[0]

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.])

In [30]:
y_test_categorical=keras.utils.to_categorical(
    y_test, num_classes=10
)
y_test_categorical[0]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [52]:
model=keras.Sequential([
    keras.layers.Flatten(input_shape=(32,32,3)),
    keras.layers.Dense(3000,activation="relu"),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1000,activation="relu"),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(10,activation="sigmoid"),
])
model.compile(optimizer="SGD",loss="categorical_crossentropy",metrics=["accuracy"])
model.fit(x_train_scaled,y_train_categorical,epochs=5)

Epoch 1/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 42s 26ms/step - accuracy: 0.2344 - loss: 2.1134
Epoch 2/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 37s 24ms/step - accuracy: 0.3383 - loss: 1.8382
Epoch 3/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 37s 24ms/step - accuracy: 0.3714 - loss: 1.7610
Epoch 4/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 39s 25ms/step - accuracy: 0.3936 - loss: 1.7069
Epoch 5/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 41s 26ms/step - accuracy: 0.4112 - loss: 1.6730


In [32]:
model.summary

<bound method Model.summary of <Sequential name=sequential_2, built=True>>

In [33]:
np.argmax(model.predict(x_test_scaled)[9])

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step


1

In [34]:
classes[y_test[9][0]]

'automobile'

In [35]:
model.summary(
    line_length=None,
    positions=None,
    print_fn=None,
    expand_nested=False,
    show_trainable=False,
    layer_range=None,
)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten_2 (Flatten)             │ (None, 3072)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 3000)           │     9,219,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1000)           │     3,001,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 10)             │        10,010 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12,230,012 (46.65 MB)

 Trainable params: 12,230,010 (46.65 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)